// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalNote.Models;

namespace PersonalNote.Migrations
{
    [DbContext(typeof(WorkoutDBContext))]
    [Migration("20190407014225_AddedJournal")]
    partial class AddedJournal
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("PersonalNote.Models.JournalReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Notes")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("JournalReport");
                });

            modelBuilder.Entity("PersonalNote.Models.WorkoutReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("Calories");

                    b.Property<string>("Category")
                        .IsRequired();

                    b.Property<string>("ItemName")
                        .IsRequired();

                    b.Property<string>("Notes")
                        .IsRequired();

                    b.Property<DateTime>("WorkoutDate");

                    b.HasKey("Id");

                    b.ToTable("WorkoutReport");
                });
#pragma warning restore 612, 618
        }
    }
}
